#!/usr/bin/env python3

import argparse
import json
import os
from pprint import pprint


def main(matrix_file, include, exclude):
    matrix = json.load(matrix_file)

    if include:
        matrix['include'] = json.loads(include)

    if exclude:
        matrix['exclude'] = json.loads(exclude)

    if os.environ.get('GITHUB_ACTIONS') == 'true':
        if os.environ.get('GITHUB_OUTPUT'):
            with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='UTF-8') as f:
                f.write(f'matrix={json.dumps(matrix)}')

    pprint(matrix)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('matrix', type=argparse.FileType('r', encoding='UTF-8'))
    parser.add_argument('--include', required=False)
    parser.add_argument('--exclude', required=False)

    args = parser.parse_args()

    main(args.matrix, args.include, args.exclude)
