#!/usr/bin/env python3

import argparse
import json
import os
from urllib.request import urlopen
from pprint import pprint


def main(matrix_url, include, exclude):
    with urlopen(matrix_url) as response:
        matrix = json.load(response)

    if include:
        matrix['include'] = json.loads(include)

    if exclude:
        matrix['exclude'] = json.loads(exclude)

    if os.environ.get('GITHUB_ACTIONS') == 'true':
        if os.environ.get('GITHUB_OUTPUT'):
            with open(os.environ['GITHUB_OUTPUT'], 'a', encoding='UTF-8') as f:
                f.write(f'matrix={json.dumps(matrix)}')

    pprint(matrix)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('matrix_url')
    parser.add_argument('--include', required=False)
    parser.add_argument('--exclude', required=False)

    args = parser.parse_args()

    main(args.matrix_url, args.include, args.exclude)
